name: publishpublish
run-name: ${{ github.actor }} build new image
on: [push]
jobs:
       publish-postgres-image:
              runs-on: ubuntu-latest
              steps:
                     - uses: actions/checkout@v2
                     - uses: docker/login-action@v1
                       with:
                              registry: ghcr.io
                              username: ${{ github.actor }}
                              password: ${{ secrets.GITHUB_TOKEN }}
                     - name: Build the Postgres 16 Docker image
                       run: |
                              timetag=(`date +%Y%M%d`)
                              docker build . --tag ghcr.io/odoonix/postgres:16.${timetag} --tag ghcr.io/odoonix/postgres:16
                              docker push ghcr.io/odoonix/postgres:16
                              docker push ghcr.io/odoonix/postgres:16.${timetag}
